---

- include: sysctl.yaml

- include: dnsmasq.yaml
- include: hostapd.yaml

- include: traffic_shaping.yaml
- include: ad_filtering.yaml

- name: Install gateway packages
  apt: pkg={{ item }} state=present
  with_items:
    - pppoeconf
