---
- name: Copy over the firewall script
  copy: src=firewall dest=/etc/firewall owner=root group=root mode=0755
  notify: Restart firewall

- name: Make sure the firewall script gets run at boot time
  lineinfile: dest=/etc/rc.local line='/etc/firewall start'
              insertbefore='exit 0' state=present

- name: Copy over the traffic control script
  copy: src=traffic_control dest=/etc/traffic_control
        owner=root group=root mode=0755
#  notify: Restart traffic control

- name: Make sure the traffic control script gets run at boot time
  lineinfile: dest=/etc/rc.local line='/etc/traffic_control start'
              insertbefore='exit 0' state=present
