---

# iptables stuff

- name: Copy firewall config
  template: src=firewall.j2 dest=/etc/firewall
            owner=root group=root mode=0755
  notify: Restart firewall

- name: Enable firewall config
  lineinfile: dest=/etc/rc.local insertbefore='exit 0'
              line='/etc/firewall start' state=present

# tc stuff

- name: Copy traffic control config
  copy: src=traffic_control dest=/etc/traffic_control
        owner=root group=root mode=0755
#  notify: Restart traffic control

- name: Enable traffic control config
  lineinfile: dest=/etc/rc.local insertbefore='exit 0'
              line='/etc/traffic_control start' state=present

# sysctl stuff

- name: Enable IPv4 forwarding
  lineinfile: dest=/etc/sysctl.d/local.conf create=yes
              line='net.ipv4.ip_forward=1' state=present
  notify: Restart procps

- name: Enable IPv6 forwarding
  lineinfile: dest=/etc/sysctl.d/local.conf create=yes
              line='net.ipv6.conf.all.forwarding=1' state=present
  notify: Restart procps
