---
- include: firewall.yml
- include: dnsmasq.yml
- include: hostapd.yml
#- include: wireless.yml

- name: Install gateway packages
  apt: pkg={{ item }} state=present
  with_items:
    - pppoeconf
    - wireless-tools
