---

- include: hibernate.yml

- include: firefox.yml
- include: thunderbird.yml
- include: libreoffice.yml

- include: sshfs.yml
- include: hdhomerun.yml

#- include: adb.yml
#- include: heimdall.yml

#- include: chirp-daily.yml
#- include: gqrx.yml

- name: Install useful clicky packages
  apt: pkg={{ item }} state=present
  with_items:
    - gitk
    - vim-gtk
    - build-essential
    - keepassx
    - librecad
    - inkscape
#    - blender
#    - vlc
#    - virtualbox
