---

- name: Install firewall
  template: src=firewall.j2 dest=/etc/firewall
            owner=root group=root mode=0755
  notify: Restart firewall

- name: Enable firewall
  lineinfile: dest=/etc/rc.local insertbefore='exit 0'
              line='/etc/firewall start' state=present

- name: Enable IPv4 forwarding
  lineinfile: dest=/etc/sysctl.d/local.conf create=yes
              line='net.ipv4.ip_forward=1' state=present
  when: gateway
  notify: Restart procps

- name: Enable IPv6 forwarding
  lineinfile: dest=/etc/sysctl.d/local.conf create=yes
              line='net.ipv6.conf.all.forwarding=1' state=present
  when: gateway
  notify: Restart procps
