---
- name: copy over the firewall script
  copy: src=firewall dest=/etc/firewall owner=root group=root mode=0755
  notify: restart firewall

- name: make sure the firewall script gets run at boot time
  lineinfile: dest=/etc/rc.local line='/etc/firewall start'
              insertbefore='exit 0' state=present

- name: turn off sudo passwords for members of the sudo group
  lineinfile: dest=/etc/sudoers.d/99-sudoers create=yes
              line='%sudo ALL=(ALL) NOPASSWD:ALL' state=present

- name: dist-upgrade
  apt: update_cache=yes upgrade=dist
  tags: upgrade

- name: install essential packages needed on all machines
  apt: pkg="{{ item }}" state=present
  with_items:
    - screen
    - git
    - ansible
