---
- name: Copy over the firewall script
  copy: src=firewall dest=/etc/firewall owner=root group=root mode=0755
  notify: Restart firewall

- name: Make sure the firewall script gets run at boot time
  lineinfile: dest=/etc/rc.local line='/etc/firewall start'
              insertbefore='exit 0' state=present

- name: Turn off sudo passwords for members of the ghost group
  lineinfile: dest=/etc/sudoers.d/99-ghost create=yes
              line='%ghost ALL=(ALL) NOPASSWD:ALL' state=present

- name: Disable password login for the ghost user
  user: name=ghost password='!' state=present

- name: dist-upgrade
  apt: upgrade=dist
# apt: update_cache=yes upgrade=dist

- name: Re-enable hibernate
  copy: src=com.ubuntu.enable-hibernate.pkla
        dest=/var/lib/polkit-1/localauthority/50-local.d/com.ubuntu.enable-hibernate.pkla

- name: Install some essential administration packages needed on all machines
  apt: pkg="{{ item }}" state=present
  with_items:
    - screen
    - git
    - ansible
    - vim
    - vim-scripts
    - ethtool

# In older Debian, 'git' was called 'git-core'
# when: ansible_distribution == 'Debian' and
#       ansible_distribution_version <= '7.0'
