---

- name: Turn off sudo passwords for members of the ghost group
  lineinfile: dest=/etc/sudoers.d/99-ghost create=yes
              line='%ghost ALL=(ALL) NOPASSWD:ALL' state=present

- name: Disable password login for the ghost user
  user: name=ghost password='!' state=present

- include: firewall.yml

- name: Perform a dist-upgrade
  apt: update_cache=yes upgrade=dist cache_valid_time=43200  # 12h

- name: Install some essential administration packages needed on all machines
  apt: pkg={{ item }} state=present
  with_items:
    - byobu
    - rsync
    - git
    - ethtool

- include: vim.yml

# In older Debian, 'git' was called 'git-core'
# when: ansible_distribution == 'Debian' and
#       ansible_distribution_version <= '7.0'
