---
- name: Install gqrx
  apt: pkg=gqrx-sdr state=present

- name: Blacklist the dvb kernel module
  kernel_blacklist: blacklist_file=/etc/modprobe.d/blacklist-rtlsdr.conf
                    name=dvb_usb_rtl28xxu state=present

- name: Unload the dvb kernel module
  modprobe: name=dvb_usb_rtl28xxu state=absent

# add-apt-repository ppa:gqrx/snapshots
