---
- name: Install libreoffice
  apt: pkg={{ item }} state=present
  with_items:
    - libreoffice
    - libreoffice-pdfimport

- name: Cull abiword and gnumeric
  apt: pkg={{ item }} state=absent purge=yes
  with_items:
    - abiword
    - gnumeric
