---
- include: firewall.yml
- include: hibernate.yml

- include: web_browser.yml
- include: libreoffice.yml

#- include: adb.yml
#- include: heimdall.yml

#- include: chirp-daily.yml
#- include: gqrx.yml

- name: Install useful clicky packages
  apt: pkg={{ item }} state=present
  with_items:
    - gitk
    - build-essential
    - keepassx
    - librecad
    - inkscape
#    - blender
#    - vlc
#    - sshfs
#    - virtualbox

- name: Install other Ubuntu packages
  apt: pkg={{ item }} state=present
  with_items:
    - thunderbird
    - enigmail
  when: ansible_distribution == 'Ubuntu'

- name: Install other Debian packages
  apt: pkg={{ item }} state=present
  with_items:
    - icedove
    - enigmail
  when: ansible_distribution == 'Debian'
